name: Changelog
on:
  workflow_dispatch:
    inputs:
      noIncrement:
        description: "Создать релиз без увеличения версии и публикации в npm"
        required: false
        default: false
        type: boolean
      bumpMode:
        description: "Режим обновления версии. auto - автоматически на основе списка изменений, major - увеличение мажорной версии, minor - увеличение минорной версии, patch - выпуск патча"
        required: false
        default: auto
        type: choice
        options:
          - auto
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release with Increment and Publishing
        if: inputs.noIncrement == false && inputs.bumpMode == 'auto'
        run: yarn release --changelog

      - name: Release with Increment as ${{ inputs.bumpMode }} and Publishing
        if: inputs.noIncrement == false && inputs.bumpMode != 'auto'
        run: yarn release ${{ inputs.bumpMode }} --changelog

      - name: Release Without Increment and Publishing
        if: inputs.noIncrement == true
        run: yarn release --no-increment --no-npm.publish --changelog --dry-run
